services:
  service:
    build: .
    ports:
      - "8081:8080"
    depends_on:
      postgres:
        restart: true
        condition: service_healthy

  postgres:
    image: postgres:16.4
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U rat -d ${POSTGRES_DB}"]
      interval: 1s
      timeout: 5s
      retries: 10

volumes:
  pgdata:
