# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23.2'

    - name: Gen docs
      run: go install github.com/swaggo/swag/cmd/swag@latest
      run: swag init -g internal/controllers/http/v1/router.go

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v --race ./...
